# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-27 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foo_name', models.CharField(max_length=100)),
                ('foo_description', models.TextField(max_length=1000)),
                ('foo_time_created', models.DateTimeField(auto_now_add=True)),
                ('foo_time_changed', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
